[package]
name = "bot"
version = "0.0.1"
edition = "2024"

[[bin]]
name = "Bangboo"
path = "src/main.rs"

[dependencies]
twilight-cache-inmemory = { version = "0.17" }
twilight-gateway = { version = "0.17" }
twilight-http = { version = "0.17" }
twilight-model = { version = "0.17" }
twilight-standby = { version = "0.17" }
twilight-mention = { version = "0.17" }
twilight-util = { version = "0.17", features = ["builder", "snowflake"] }
twilight-gateway-queue = { version = "0.17" }
async-trait = { version = "0.1" }
colored = { version = "3" }
config = { version = "0.15" }
discloud-rs = { git = "https://github.com/Cesio137/discloud-rs.git", branch = "dev" }
dotenvy = { version = "0.15" }
genai = { version = "0.4" }
# glob = { version = "0.3" }
once_cell = { version = "1.21" }
regex = { version = "1.12" }
reqwest = { version = "0.12" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
skia-safe = { version = "0.90", features = ["textlayout", "gl"] }
tokio = { version = "1.48", features = ["macros", "rt-multi-thread", "signal"] }
chrono = "0.4.42"
log = "0.4.28"
