[package]
name = "bot"
version = "0.0.1"
edition = "2024"

[[bin]]
name = "Bangboo"
path = "src/main.rs"

[dependencies]
serenity = { git = "https://github.com/serenity-rs/serenity.git", branch = "next", features = ["collector", "model"] }
async-trait = { version = "0.1" }
anyhow = { version = "1.0" }
colored = { version = "3" }
config = { version = "0.15" }
discloud-rs = { git = "https://github.com/Cesio137/discloud-rs.git", branch = "dev" }
dotenvy = { version = "0.15" }
genai = { version = "0.4" }
glob = { version = "0.3" }
image = { version = "0.25" }
#imghash = { version = "1.5" }
once_cell = { version = "1.21" }
regex = { version = "1.12" }
reqwest = { version = "0.12" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
skia-safe = { version = "0.90", features = ["textlayout", "gl"] }
tokio = { version = "1.48", features = ["macros", "rt-multi-thread", "signal"] }
chrono = { version = "0.4" }